// https://github.com/yuphin/Lumen

#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../commons.h"

layout(constant_id = 0) const int SIZE = 4096;

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(set = 1, binding = 0) uniform sampler2D PingImage;
layout(set = 1, binding = 1, rgba32f) uniform image2D PongImage;
layout(binding = 2) uniform sampler2D KernalImage;

layout(push_constant, std140) uniform PushConstant {
	int vertical;
	int inverseFFT;
} pc;

const int RADIX = 2;
const float PI = 3.14159265359;

shared float s_data_real[SIZE * RADIX];
shared float s_data_imag[SIZE * RADIX];

vec2 complex_mul(vec2 a, vec2 b)
{
	return vec2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}

void butterfly(vec2 data[RADIX], vec2 wp, out vec2 result[RADIX])
{
	result[0] = data[0] + data[1];
	result[1] = complex_mul(wp, data[0] - data[1]);
}

void exchange(uint fixed_idx, uint stride, uint T, vec2 data_processed[RADIX], out vec2 data[RADIX])
{
	for (int r = 0; r < RADIX; r++)
	{
		s_data_real[fixed_idx + r * stride] = data_processed[r].x;
		s_data_imag[fixed_idx + r * stride] = data_processed[r].y;
	}

	memoryBarrierShared();
	barrier();

	for (int r = 0; r < RADIX; r++)
	{
		data[r].x = s_data_real[gl_LocalInvocationID.x + r * T];
		data[r].y = s_data_imag[gl_LocalInvocationID.x + r * T];
	}
}

void fft_shared_img(bool is_rg, ivec2 coords[RADIX], inout vec2 data[RADIX])
{
	const uint N = RADIX * gl_WorkGroupSize.x;
	const uint N_DIV_RADIX = gl_WorkGroupSize.x;

	const uint j = gl_LocalInvocationID.x;

	if (pc.inverseFFT == 1 || pc.vertical == 1)
	{
		if (is_rg)
		{
			for (int r = 0; r < RADIX; r++)
			{
				data[r] = imageLoad(PongImage, coords[r]).rg;
			}
		}

		else
		{
			for (int r = 0; r < RADIX; r++)
			{
				data[r] = imageLoad(PongImage, coords[r]).ba;
			}
		}
	}

	else
	{
		if (is_rg)
		{
			for (int r = 0; r < RADIX; r++)
			{
				data[r] = texelFetch(PingImage, coords[r], 0).rg;
			}
		}

		else
		{
			for (int r = 0; r < RADIX; r++)
			{
				data[r] = texelFetch(PingImage, coords[r], 0).ba;
			}
		}
	}

	for (uint stride = 1; stride < N; stride *= RADIX)
	{
		const uint stride_factor = stride * uint(j / stride);
		float angle = 2 * PI * stride_factor / N;

		if (pc.inverseFFT == 1)
		{
			angle *= -1;
		}

		const vec2 wp = vec2(cos(angle), -sin(angle));
		vec2 data_processed[RADIX];
		butterfly(data, wp, data_processed);
		const uint fixed_idx = j % stride + stride_factor * RADIX;
		memoryBarrierShared();
		barrier();
		exchange(fixed_idx, stride, N_DIV_RADIX, data_processed, data);
	}

	if (pc.inverseFFT == 1)
	{
		for (int r = 0; r < RADIX; r++)
		{
			data[r] /= N;
		}
	}
}

void main()
{
	ivec2 coords[RADIX];

	const uint N_DIV_RADIX = gl_WorkGroupSize.x;
	const uint N = RADIX * gl_WorkGroupSize.x;
	ivec2 IMG_DIMS;

	if (pc.vertical == 1)
	{
		IMG_DIMS = ivec2(gl_NumWorkGroups.x , N);

		for (int r = 0; r < RADIX; r++)
		{
			coords[r] = ivec2(gl_GlobalInvocationID.x / N_DIV_RADIX, gl_GlobalInvocationID.x % N_DIV_RADIX + r * N_DIV_RADIX);
		}
	}

	else
	{
		IMG_DIMS = ivec2(N, gl_NumWorkGroups.x);

		for (int r = 0; r < RADIX; r++)
		{
			coords[r] =
				ivec2(gl_GlobalInvocationID.x % N_DIV_RADIX + r * N_DIV_RADIX, gl_GlobalInvocationID.x / N_DIV_RADIX);
		}
	}

	vec2 data_rg[RADIX], data_ba[RADIX];
	fft_shared_img(true, coords, data_rg);
	fft_shared_img(false, coords, data_ba);

	if (pc.vertical == 1 && pc.inverseFFT == 0)
	{
		vec4 kernel_vals[RADIX];

		for (int r = 0; r < RADIX; r++)
		{
			kernel_vals[r] = texelFetch(KernalImage, coords[r], 0).rgba;
		}
		// Not necessary since we're applying 2 in 1 trick
		// rg.xy = complex_mul(rg.xy, kernel_val.rg);
		// rg.zw = complex_mul(rg.zw, kernel_val_strided.rg);

		// ba.xy = complex_mul(ba.xy, kernel_val.ba);
		// ba.zw = complex_mul(ba.zw, kernel_val_strided.ba);

		for (int r = 0; r < RADIX; r++)
		{
			data_rg[r] *= kernel_vals[r].x;
			data_ba[r] *= kernel_vals[r].z;
		}
	}

	for (int r = 0; r < RADIX; r++)
	{
		imageStore(PongImage, coords[r], vec4(data_rg[r], data_ba[r]));
	}
}