#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../shared_with_shaders.h"

layout(set = 0, binding = 0, rgba32f) uniform image2D ResultImage;

layout(set = 0, binding = 1, std140) uniform Data {
	DitheringParams params;
};

layout(local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec3 color = imageLoad(ResultImage, coord).rgb;

	mat4 thresholdMap = mat4(
		0.0,  8.0,  2.0,  10.0,
		12.0, 4.0,  14.0, 6.0,
		3.0,  11.0, 1.0,  9.0,
		15.0, 7.0,  13.0, 5.0
	);

	ivec2 mapCoord = coord % 4;
	float M = thresholdMap[mapCoord.x][mapCoord.y] / 16.0 - 0.5;
	color = floor(color * float(params.bands - 1) + 0.5) / float(params.bands - 1);

	imageStore(ResultImage, coord, vec4(color + M * params.spread, 1.0));
}