#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../shared_with_shaders.h"

layout(set = 0, binding = 0, rgba32f) uniform image2D ResultImage;

layout(set = 0, binding = 1, std140) uniform Data {
	VignetteParams params;
};

layout(local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = vec2(coord) / vec2(imageSize(ResultImage));
	vec2 duv = uv - 0.5;

	vec3 color = imageLoad(ResultImage, coord).rgb;
	float vignette = 1.0 - length(duv);

	imageStore(ResultImage, coord, vec4(color * pow(vignette, params.intensity), 1.0));
}